name: Create pages
run-name: Build all Inferno ports
on: [push, workflow_dispatch]

jobs:
  call-apollo3-workflow:
    uses: ./.github/workflows/apollo3.yml
  call-samd51-workflow:
    uses: ./.github/workflows/samd51.yml
  call-stm32f405-workflow:
    uses: ./.github/workflows/stm32f405.yml
  call-teensy41mm-workflow:
    uses: ./.github/workflows/teensy41mm.yml

  call-hosted-386-workflow:
    uses: ./.github/workflows/hosted-386.yml

  make-pages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Look around
        run: tree
