name: Create pages
run-name: Build all Inferno ports
on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-apollo3-workflow:
    uses: ./.github/workflows/apollo3.yml
  call-rpi-workflow:
    uses: ./.github/workflows/rpi.yml
  call-samd51-workflow:
    uses: ./.github/workflows/samd51.yml
  call-stm32f405-workflow:
    uses: ./.github/workflows/stm32f405.yml
  call-teensy41mm-workflow:
    uses: ./.github/workflows/teensy41mm.yml

  call-hosted-386-workflow:
    uses: ./.github/workflows/hosted-386.yml

  make-pages:
    name: Make a site with the artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    needs:
      - call-apollo3-workflow
      - call-rpi-workflow
      - call-samd51-workflow
      - call-stm32f405-workflow
      - call-teensy41mm-workflow
      - call-hosted-386-workflow

    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Look around
        run: tree
      - name: Move the data
        run: |
          mv *-kernel _site/
      - name: Upload GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v2

  deploy:

    needs: make-pages
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
