name: Create pages
run-name: Build all Inferno ports
on: [push, workflow_dispatch]

jobs:
  call-apollo3-workflow:
    uses: ./.github/workflows/apollo3.yml
  call-samd51-workflow:
    uses: ./.github/workflows/samd51.yml
  call-stm32f405-workflow:
    uses: ./.github/workflows/stm32f405.yml
  call-teensy41mm-workflow:
    uses: ./.github/workflows/teensy41mm.yml
