name: Create pages
run-name: Build Inferno
on: [push, workflow_dispatch]

jobs:
  call-apollo3-workflow:
    uses: dboddie/inferno-ports/.github/workflows/apollo3.yml@main
  call-samd51-workflow:
    uses: dboddie/inferno-ports/.github/workflows/samd51.yml@main
  call-stm32f405-workflow:
    uses: dboddie/inferno-ports/.github/workflows/stm32f405.yml@main
  call-teensy41mm-workflow:
    uses: dboddie/inferno-ports/.github/workflows/teensy41mm.yml@main
