name: test-rpi-builds
run-name: Build Inferno
on: [workflow_call, workflow_dispatch]

jobs:
  clone-and-build-repo:
    runs-on: ubuntu-24.04
    steps:
      - name: Get dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libc6-dev-i386
      - name: Clone the repository
        run: git clone https://github.com/dboddie/inferno-rpi.git inferno-os
      - name: Build the host system
        run: |
          cd $GITHUB_WORKSPACE/inferno-os
          sed -ri 's|/usr\/inferno|'$PWD'|' mkconfig
          sed -ri 's/SYSHOST=Plan9/SYSHOST=Linux/' mkconfig
          sed -ri 's/#OBJTYPE/OBJTYPE/' mkconfig
          sed -ri 's/OBJTYPE=\$/#OBJTYPE=\$/' mkconfig
          sed -ri 's/\temu/#\temu/' mkfile
          sed -ri 's/cp irpi/#cp irpi/' os/rpi/mkfile
          ./makemk.sh
          export PATH=$PWD/Linux/386/bin/:$PATH
          mk nuke
          mk mkdirs
          mk install
      - name: Build a port
        run: |
          cd $GITHUB_WORKSPACE/inferno-os
          export PATH=$PWD/Linux/386/bin/:$PATH
          cd appl/tiny
          mk install
          cd ../..
          cd os/rpi
          mk
      - name: Archive the build product
        uses: actions/upload-artifact@v4
        with:
          name: rpi-kernel
          path: |
            inferno-os/os/rpi/kernel.bin
